"""renew columns

Revision ID: 4a7e3c7bea5d
Revises: 56cd6d6e819f
Create Date: 2026-02-03 04:32:20.592900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a7e3c7bea5d'
down_revision: Union[str, Sequence[str], None] = '56cd6d6e819f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Cart', 'Product', ['product_name'], ['name'])
    op.create_foreign_key(None, 'Order', 'User', ['user_id'], ['id'])
    op.create_foreign_key(None, 'Order', 'Product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Order', type_='foreignkey')
    op.drop_constraint(None, 'Order', type_='foreignkey')
    op.drop_constraint(None, 'Cart', type_='foreignkey')
    # ### end Alembic commands ###
