"""renew columns

Revision ID: 56cd6d6e819f
Revises: 69f6263415c0
Create Date: 2026-02-03 04:30:14.903090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56cd6d6e819f'
down_revision: Union[str, Sequence[str], None] = '69f6263415c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Cart', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'Product', ['product_name'], ['name'])

    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'Product', ['product_id'], ['id'])
        batch_op.create_foreign_key(None, 'User', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('Cart', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
