"""renew columns

Revision ID: 69f6263415c0
Revises: 5c6a46f76924
Create Date: 2026-02-03 04:24:52.448515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69f6263415c0'
down_revision: Union[str, Sequence[str], None] = '5c6a46f76924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cart', sa.Column('product_name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'Cart', 'Product', ['product_name'], ['name'])
    op.create_foreign_key(None, 'Order', 'Product', ['product_id'], ['id'])
    op.create_foreign_key(None, 'Order', 'User', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Order', type_='foreignkey')
    op.drop_constraint(None, 'Order', type_='foreignkey')
    op.drop_constraint(None, 'Cart', type_='foreignkey')
    op.drop_column('Cart', 'product_name')
    # ### end Alembic commands ###
