"""add user columns

Revision ID: bb7dbd598d01
Revises: 2fa864db2f89
Create Date: 2026-02-03 02:22:17.433250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb7dbd598d01'
down_revision: Union[str, Sequence[str], None] = '2fa864db2f89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('loyalty_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'loyalty_score')
    # ### end Alembic commands ###
