"""create quantity column

Revision ID: ffac0355b198
Revises: 435186071c74
Create Date: 2026-02-03 03:46:46.319987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffac0355b198'
down_revision: Union[str, Sequence[str], None] = '435186071c74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cart', sa.Column('quantity', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Order', 'User', ['user_id'], ['id'])
    op.create_foreign_key(None, 'Order', 'Product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Order', type_='foreignkey')
    op.drop_constraint(None, 'Order', type_='foreignkey')
    op.drop_column('Cart', 'quantity')
    # ### end Alembic commands ###
